{{- if .Values.localUrl }}
apiVersion: batch.test.bdap.com/v1
kind: MPIJob
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mpijob.labels" . | nindent 4 }}
spec:
  numWorkers: {{ .Values.numWorkers }}
  launcherTemplate:
    spec:
      restartPolicy: Never
      containers:
        - args:
            - mkdir {{ .Values.localRepoName }} && cd {{ .Values.localRepoName }} &&
              {{- if ne .Values.workDir "." }}
              mkdir {{ .Values.workDir }} && cd {{ .Values.workDir }} &&
              {{- end}}
              {{- range .Values.commands }}
              horovodrun -np {{ $.Values.numWorkers }} --hostfile $OMPI_MCA_orte_default_hostfile {{ . }} &&
              {{- end }}
              echo "end"
          command:
            - /bin/bash
            - -c
          image: {{ .Values.masterImage }}
          name: master
      {{- with .Values.masterTolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  workerTemplate:
    {{- if .Values.gang }}
    metadata:
      labels:
        pod-group.scheduling.bdap.com/podgroup-configmap: {{ .Values.name }}-pg
    {{- end }}
    spec:
      {{- if .Values.gang }}
      schedulerName: {{ .Values.gangSchedulerName }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - args:
          - while ! cd {{ .Values.localRepoName }}; do echo "Waiting code directory"; sleep 3; done &&
            {{- if ne .Values.workDir "." }}
            cd {{ .Values.workDir }} &&
            {{- end}}
            {{- if .Values.pipInstall }}
            pip install -r requirements.txt &&
            {{- end }}
            touch /ready.txt &&
            sleep infinity
          command:
            - /bin/bash
            - -c
          image: {{ .Values.workerImage }}
          name: worker
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.gpuPerWorker }}
          readinessProbe:
            {{- toYaml .Values.workerReadinessProbe | nindent 12 }}
      {{- with .Values.workerTolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}