{{- if .Values.gang }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-pg
  namespace: {{ .Values.namespace }}
data:
  minAvailable: {{ .Values.numWorkers | quote }}
  scheduleTimeoutSeconds: {{ .Values.scheduleTimeoutSeconds | quote }}
{{- end }}