# must overwrite
name: "default-mpijob"
namespace: "default"
numWorkers: 3
gitUrl: https://github.com/FFFFFaraway/sample-python-train.git
commands:
- python generate_data.py
- python main.py

# better to have a look
masterImage: farawaya/horovod-torch-cpu
workerImage: farawaya/horovod-torch-cuda113
# gitRepoName: MPI-Operator
gpuPerWorker: 1
pipInstall: false
gang: false
gangSchedulerName: gang-scheduler
workDir: .

masterTolerations: [ ]
#  - effect: NoSchedule
#    key: gpu
#    operator: Exists
workerTolerations:
  - effect: NoSchedule
    key: gpu
    operator: Exists
workerReadinessProbe:
  exec:
    command:
      - cat
      - /ready.txt
  initialDelaySeconds: 30
  periodSeconds: 5

scheduleTimeoutSeconds: 20
